In [1]:
import numpy as np # array creation, arry elements are seperated by white space

arr = np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [2]:
l = [10,20,30]
print(l)
print(type(l)) # elemsta are sepearted by ,

[10, 20, 30]
<class 'list'>


In [3]:
arr = np.array([10, 1.1,20,30, "BLR"]) # if we try to create a array with dufferent datatype , it coverts the entire array to a higher data type array
print(arr)

['10' '1.1' '20' '30' 'BLR']


In [4]:
#Operations on Array

a1 = np.array([10,20,30])
print(a1)

a2 = a1+2


print(a2)

[10 20 30]
[12 22 32]


In [5]:
#Operations on List

a1 =[10,20,30]
print(a1)
a2 = a1*3
print(a2)

[10, 20, 30]
[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [6]:
# memory consumption

import sys

l = [10,20,30]
print(sys.getsizeof(l))

a = np.array([10,20,30])
print(a.itemsize)
print(a.nbytes)

88
8
24


In [7]:
# creating ndarray

a = np.array([10,20,30,40])

print(a)
print(type(a))
print(a.ndim)

[10 20 30 40]
<class 'numpy.ndarray'>
1


In [8]:
#o dim array
a= np.array(44)
print(a)
print(type(a))
print(a.ndim)

44
<class 'numpy.ndarray'>
0


In [9]:
#2 dim array
a= np.array([[10,20,30]])
print(a)
print(type(a))
print(a.ndim)

[[10 20 30]]
<class 'numpy.ndarray'>
2


In [10]:
#2 dim array
a= np.array([[[10,20,30]]])
print(a)
print(type(a))
print(a.ndim)

[[[10 20 30]]]
<class 'numpy.ndarray'>
3


In [11]:
#n dimm array

n = int(input("enter the dim"))

a= np.array([10,20,30], ndmin=n)
print(a)
print(a.ndim)

enter the dim1
[10 20 30]
1


In [12]:
a = np.array([[10,20,30],[40,50,60]])
print(a)
print(a.ndim)

[[10 20 30]
 [40 50 60]]
2


In [13]:
a = np.array([[10,20,30],[40,50,60]])

print(a)

print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)
print(a.min())
print(a.max())
print(a.sum())

print(a.sum(axis=0))
print(a.sum(axis=1))

print(a.mean())
print(a.std())
print(a.var())

[[10 20 30]
 [40 50 60]]
(2, 3)
6
int64
8
48
10
60
210
[50 70 90]
[ 60 150]
35.0
17.07825127659933
291.6666666666667


In [14]:
# create a nd array with all zeros

a = np.zeros(4)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[0. 0. 0. 0.]
float64
1
(4,)


In [15]:
# create a nd array with all zeros

a = np.zeros((4,3), dtype='int')
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
int64
2
(4, 3)


In [16]:
# create a nd array with all zeros

a = np.ones((4,3), dtype='int')
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
int64
2
(4, 3)


In [30]:
# create a nd array with all zeros

a = np.ones((4,3), dtype='float') * 5
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
float64
2
(4, 3)


In [18]:
#arange function
a = np.arange(10)
print(a)
print(a.ndim)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
1
(10,)


In [19]:
#arange function
a = np.arange(2,10,2,dtype = 'float')
print(a)
print(a.ndim)
print(a.shape)

[2. 4. 6. 8.]
1
(4,)


In [20]:

#linspace- generate numbers in linear space

a = np.linspace(1,2,5)
print(a)

[1.   1.25 1.5  1.75 2.  ]


In [21]:
# Create a 1D array using linspace
linear_space = np.linspace(1, 10, 12)  # Generates 12 numbers between 1 and 10

# Reshape the 1D array into a 2D array (e.g., 3 rows and 4 columns)
two_d_array = linear_space.reshape(3, 4)

print(two_d_array)

[[ 1.          1.81818182  2.63636364  3.45454545]
 [ 4.27272727  5.09090909  5.90909091  6.72727273]
 [ 7.54545455  8.36363636  9.18181818 10.        ]]


In [22]:
#Matrix

mat = np.matrix([[1,2,3],[4,5,6]])
print(mat)
print(type(mat))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [23]:
# transpose of a mtrix
mat = np.matrix([[1,2,3],[4,5,6]])
print(mat)

trans = mat.T
print(mat)
print(trans)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [24]:
# identity matrix

mat = np.identity(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
a = np.diag([10,20,30])
print(a)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [33]:
# random numbers

a = np.random.random(10)
print(a)

[0.1483603  0.47505143 0.30712905 0.14488289 0.94801304 0.1565881
 0.14946652 0.34233607 0.46777546 0.82222617]


In [27]:
a = np.random.random((3,3,))
print(a)

[[0.466162   0.1740732  0.08418313]
 [0.86588506 0.10361758 0.25217651]
 [0.13843529 0.05402752 0.85711045]]


In [35]:
r = np.random.randint(11,150, size =5)
print(r)

[ 63 117  66  78 148]


In [38]:
r = np.random.uniform(1,100, size=10)
print(r)

[57.17402785 39.17372115 27.47422047 96.46902955 38.81836969 77.53785706
 68.1748512   7.47136632 56.09657183 14.58310862]


In [43]:
# choice

k = np.random.choice([10,20,30,40],size=3)
print(k)

[40 40 40]


In [48]:
# choice fun- without duplicates, default value = True
k = np.random.choice([10,20,30,40],size=3, replace = False)
print(k)

[30 10 20]


In [53]:
a = np.array([22,33,44])
prob= np.array([.5,.4,.1]) # the sum must be equal to 1(100%)

k= np.random.choice(a, p=prob, size=10)
print(k)

[33 22 22 33 22 22 33 22 33 44]


In [61]:
# choosing random rows

arr_2d = np.arange(0,20).reshape(4,5)
print(arr_2d)

rowno = arr_2d.shape[0]
print(rowno)

random_rowindex = np.random.choice(rowno , size= 2, replace= False)

print(random_rowindex)

final_output = arr_2d[random_rowindex]

print(final_output)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
4
[0 1]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [64]:
# choosing random cols

arr_2d = np.arange(0,20).reshape(4,5)
print(arr_2d)

colno = arr_2d.shape[1]
print(colno)

random_colindex = np.random.choice(colno , size= 2, replace= False)

print(random_colindex)

final_output = arr_2d[:,random_colindex]

print(final_output)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
5
[3 4]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]]


In [71]:
# shuffling the array

a= np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[9 4 3 0 8 7 1 2 5 6]


In [75]:
# permutation

a = np.random.permutation(10)
print(a)

[5 2 8 0 9 1 3 6 4 7]


In [77]:
# permutation 2d array

array_2d = np.arange(0,20).reshape(4,5)
print(array_2d)

a=np.random.permutation(array_2d)
print(a)
print(array_2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 0  1  2  3  4]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [83]:
# row shuffling
array_2d = np.arange(0,20).reshape(4,5)
print(array_2d)

num_rows = array_2d.shape[0]

shuffled_index = np.random.permutation(num_rows)

shuffled_array = array_2d[shuffled_index]

print(shuffled_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [89]:
# column shuffling
array_2d = np.arange(0,20).reshape(4,5)
print(array_2d)

num_rows = array_2d.shape[1]

shuffled_index = np.random.permutation(num_rows)

shuffled_array = array_2d[:,shuffled_index]

print(shuffled_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 2  4  0  3  1]
 [ 7  9  5  8  6]
 [12 14 10 13 11]
 [17 19 15 18 16]]


In [90]:
# Grouping and Splitting

array_1d = np.arange(10)
print(array_1d)

array_2d_0 = np.arange(0,18).reshape(3,6)
print(array_2d_0)

array_2d_1 = np.arange(18,36).reshape(3,6)
print(array_2d_1)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [93]:
# concatenate row wise  axis=0 ---- row oriented
a = np.concatenate([array_2d_0, array_2d_1], axis=0)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [92]:
# concatenate row wise   axis =1 ----- col oriented
a = np.concatenate([array_2d_0, array_2d_1], axis=1)
print(a)

[[ 0  1  2  3  4  5 18 19 20 21 22 23]
 [ 6  7  8  9 10 11 24 25 26 27 28 29]
 [12 13 14 15 16 17 30 31 32 33 34 35]]


In [97]:
# np stack

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

#print(np.stack([a1,a2]))

print(np.stack([a1,a2], axis =1))

[[1 4]
 [2 5]
 [3 6]]


In [98]:
print(array_2d_0)

print(array_2d_1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [103]:

array_stacked = np.stack([array_2d_0,array_2d_1], axis =1)
print(array_stacked)
print( array_stacked.shape)

[[[ 0  1  2  3  4  5]
  [18 19 20 21 22 23]]

 [[ 6  7  8  9 10 11]
  [24 25 26 27 28 29]]

 [[12 13 14 15 16 17]
  [30 31 32 33 34 35]]]
(3, 2, 6)


In [104]:
array_stacked = np.stack([array_2d_0,array_2d_1], axis =0)
print(array_stacked)
print( array_stacked.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
(2, 3, 6)


In [106]:
array_stacked = np.stack([array_2d_0,array_2d_1], axis =-1)
print(array_stacked)
print( array_stacked.shape)

[[[ 0 18]
  [ 1 19]
  [ 2 20]
  [ 3 21]
  [ 4 22]
  [ 5 23]]

 [[ 6 24]
  [ 7 25]
  [ 8 26]
  [ 9 27]
  [10 28]
  [11 29]]

 [[12 30]
  [13 31]
  [14 32]
  [15 33]
  [16 34]
  [17 35]]]
(3, 6, 2)


In [107]:
# vstack

np.vstack([array_2d_0,array_2d_1])   # np.concatenate axis = 0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [108]:
#hstack
np.hstack([array_2d_0,array_2d_1])  # np.concatenate axiz = 1

array([[ 0,  1,  2,  3,  4,  5, 18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35]])

In [114]:
# np.split
print(array_1d)
k = np.split(array_1d , indices_or_sections=5)
print(k)
print(k[3])

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[6 7]


In [115]:
# split 2d arrays
print(array_2d_0)

np.split(array_2d_0 , indices_or_sections=3, axis =1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [116]:
# addinh axis ==== expanding the dimensions

print(array_2d_0)
print(array_2d_0.shape)
print(array_2d_0.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
(3, 6)
2


In [117]:
new_array = np.expand_dims(array_2d_0 , axis=0)
print(new_array)
print(new_array.shape)
print(new_array.ndim)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]]
(1, 3, 6)
3


In [118]:
k = np.squeeze(new_array)
print(k)
print(k.shape)
print(k.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
(3, 6)
2


In [119]:
# reorderinhg

# flip

print(array_1d)
np.flip(array_1d)     # array_1d[::-1]

[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [121]:
# flip 2d array
print(array_2d_0)
np.flip(array_2d_0, axis =0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [122]:
# flip 2d array
print(array_2d_0)
np.flip(array_2d_0, axis =1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12]])

In [123]:
#resize

print(array_2d_0)

np.resize(array_2d_0 , new_shape =11)



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
np.resize(array_2d_0 , new_shape =(4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [125]:
np.resize(array_2d_0 , new_shape =(2,5,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])